const products = [
  {
    href: 'pdp.html',
    name: 'Cups',
    formattedPrice: '$5.9',
    price: 5.9,
    imageSource: 'https://liketo.ru/upload/iblock/e0a/15021142.jpg',
    hasSalesPrice: true,
    wasPrice: '$7.9',
    wasFormattedPrice: 7.9,
    review: 4.5,
  },
  {
    href: 'pdp-item.html',
    name: 'Vases',
    formattedPrice: '$12.5',
    imageSource: 'https://multiurok.ru/img/264385/image_5856bc0025853.jpg',
    review: 5,
  },
  {
    href: 'pdp-item-2.html',
    name: 'Key-chains',
    formattedPrice: '$3.9',
    price: 3.9,
    imageSource: 'http://ae01.alicdn.com/kf/HTB1mHvRKXXXXXc1XpXXq6xXFXXXo.jpg_q50.jpg',
    hasSalesPrice: true,
    wasPrice: '$5.9',
    wasFormattedPrice: 5.9,
    review: 4.6,
  },
  {
    href: 'pdp-item-3.html',
    name: 'Magnets',
    formattedPrice: '$1.5',
    price: 1.5,
    imageSource: 'https://www.world-wide-gifts.com/images/large/00010408-ceramic-3d-magnet-from-netherlands-amsterdam-canal-houses-ceramics.jpg',
    hasSalesPrice: true,
    wasPrice: '$2.5',
    wasFormattedPrice: 2.5,
    review: 4.1,
  },
  {
    href: 'pdp-item-4.html',
    name: 'Plates',
    formattedPrice: '$22.5',
    price: 22.6,
    imageSource: 'https://i.pinimg.com/736x/90/e0/7d/90e07dd78e4a6848800adfd82c96360c.jpg',
    hasSalesPrice: true,
    wasPrice: '$31.5',
    wasFormattedPrice: 31.5,
    review: 4.3,
  },
  {
    href: 'pdp-item-5.html',
    name: 'Statuettes',
    formattedPrice: '$18.5',
    price: 18.5,
    imageSource: 'https://vintajj.ru/wa-data/public/shop/products/05/81/78105/images/184328/184328.750x0.jpg',
    review: 4.3,
  },
];

export default products;
