const products = [

  {
    href: 'pdp.html',
    name: 'Item-1',
    formattedPrice: '$5.9',
    price: 33.9,
    imageSource: 'https://liketo.ru/upload/iblock/e0a/15021142.jpg',
    hasSalesPrice: true,
    wasPrice: '$54.9',
    wasFormattedPrice: 54.9,
    review: 4.5,
  },
  {
    href: 'pdp-item.html',
    name: 'Item-5',
    formattedPrice: '$12.6',
    imageSource: 'https://multiurok.ru/img/264385/image_5856bc0025853.jpg',
    review: 5,
  },
  {
    href: 'pdp-item-2.html',
    name: 'Item-4',
    formattedPrice: '$3.9',
    price: 3.9,
    imageSource: 'http://ae01.alicdn.com/kf/HTB1mHvRKXXXXXc1XpXXq6xXFXXXo.jpg_q50.jpg',
    hasSalesPrice: true,
    wasPrice: '$3.9',
    wasFormattedPrice: 5.9,
    review: 4.6,
  },
  {
    name: 'Item-2',
    formattedPrice: '$33.9',
    price: 33.9,
    imageSource: 'src/images/products/Headphones.jpg',
    hasSalesPrice: true,
    wasPrice: '$56.9',
    wasFormattedPrice: 56.9,
    review: 4.1,
  },
  {
    href: 'pdp.html',
    name: 'Samsung Galaxy S6',
    formattedPrice: '$226',
    price: 226,
    imageSource: './images/products/galaxy-1.jpg',
    hasSalesPrice: true,
    wasPrice: '$276',
    wasFormattedPrice: 276,
    review: 4.3,
  },
  {
    name: 'Item-6',
    formattedPrice: '$699.9',
    price: 699.9,
    imageSource: '/src/images/products/SmartphoneSamsung.jpg',
    review: 2,
  },
];

export default products;
