const products = [

  {
    href: 'pdp-item-2.html',
    name: 'Item-3',
    formattedPrice: '$33.9',
    price: 33.9,
    imageSource: 'https://yandex.ru/images/search?text=%D1%87%D0%B0%D1%88%D0%BA%D0%B0&iorient=square&ncrnd=1575405467917-9840323950585784&pos=0&img_url=https%3A%2F%2Ftvoydom.ru%2Fphotos%2F1001585342%2F1001585342.jpg&rpt=simage',
    hasSalesPrice: true,
    wasPrice: '$54.9',
    wasFormattedPrice: 54.9,
    review: 4.5,
  },
  {
    href: 'pdp-item.html',
    name: 'Item-5',
    formattedPrice: '$12',
    imageSource: './src/images/products/items-new/new-item-2.jpg',
    review: 5,
  },
  {
    href: 'pdp-item-3.html',
    name: 'Item-4',
    formattedPrice: '$3.9',
    price: 3.9,
    imageSource: '../../images/products/items-new/new-item-21.jpg',
    hasSalesPrice: true,
    wasPrice: '$3.9',
    wasFormattedPrice: 5.9,
    review: 4.6,
  },
  {
    name: 'Item-2',
    formattedPrice: '$33.9',
    price: 33.9,
    imageSource: 'src/images/products/Headphones.jpg',
    hasSalesPrice: true,
    wasPrice: '$56.9',
    wasFormattedPrice: 56.9,
    review: 4.1,
  },
  {
    href: 'pdp.html',
    name: 'Samsung Galaxy S6',
    formattedPrice: '$226',
    price: 226,
    imageSource: './images/products/galaxy-1.jpg',
    hasSalesPrice: true,
    wasPrice: '$276',
    wasFormattedPrice: 276,
    review: 4.3,
  },
  {
    name: 'Item-6',
    formattedPrice: '$699.9',
    price: 699.9,
    imageSource: '/src/images/products/SmartphoneSamsung.jpg',
    review: 2,
  },
];

export default products;
